var formations = [
	{"name" : "4-2-3-1",
	"position" : 																			[["---------------------", "Manuel Neuer", "Marc-Andre ter Stegen", "Bernd Leno", "Kevin Trapp"],
	["---------------------", "Joshua Kimmich", "Antonio Rüdiger"], ["---------------------", "Jerome Boateng", "Mats Hummels", "Niklas Süle", "Antonio Rüdiger", "Matthias Ginter", "Jonathan Tah"], ["---------------------", "Jerome Boateng", "Mats Hummels", "Niklas Süle", "Antonio Rüdiger", "Matthias Ginter", "Jonathan Tah"], ["---------------------", "Jonas Hector", "Marvin Plattenhardt", "Niklas Süle", "Matthias Ginter", "Jonathan Tah"],
															["---------------------", "Sami Khedira", "Toni Kroos", "Ilkay Gündogan", "Sebastian Rudy", "Mesut Özil"],								["---------------------", "Sami Khedira", "Toni Kroos", "Ilkay Gündogan", "Sebastian Rudy", "Mesut Özil"],
				["---------------------", "Thomas Müller", "Leon Goretzka", "Julian Brandt", "Ilkay Gündogan", "Julian Draxler", "Leroy Sane", "Marco Reus", "Mesut Özil"], ["---------------------", "Thomas Müller", "Mesut Özil", "Julian Draxler", "Leon Goretzka", "Leroy Sane", "Ilkay Gündogan", "Julian Brandt"], ["---------------------", "Thomas Müller", "Mesut Özil", "Julian Draxler", "Leon Goretzka", "Leroy Sane", "Ilkay Gündogan", "Marco Reus", "Mesut Özil", "Julian Brandt"],
																							["---------------------", "Timo Werner", "Mario Gomez", "Thomas Müller", "Nils Petersen"]]
	},
	{"name" : "3-3-3-1",
	"position" :  																			[["---------------------", "Manuel Neuer", "Marc-Andre ter Stegen", "Bernd Leno", "Kevin Trapp"],
		["---------------------", "Joshua Kimmich", "Antonio Rüdiger", "Jerome Boateng", "Mats Hummels", "Niklas Süle", "Matthias Ginter", "Jonathan Tah"], ["---------------------", "Jerome Boateng", "Mats Hummels", "Niklas Süle", "Antonio Rüdiger", "Matthias Ginter", "Jonathan Tah"], ["---------------------", "Jonas Hector", "Marvin Plattenhardt", "Jerome Boateng", "Mats Hummels", "Niklas Süle", "Antonio Rüdiger", "Matthias Ginter", "Jonathan Tah"],
		["---------------------", "Joshua Kimmich", "Leon Goretzka", "Julian Brandt", "Ilkay Gündogan", "Julian Draxler", "Leroy Sane", "Marco Reus", "Mesut Özil"], ["---------------------", "Sami Khedira", "Toni Kroos", "Ilkay Gündogan", "Sebastian Rudy", "Mesut Özil"], ["---------------------", "Leon Goretzka", "Julian Brandt", "Ilkay Gündogan", "Julian Draxler", "Leroy Sane", "Marco Reus", "Mesut Özil"],
		["---------------------", "Leon Goretzka", "Julian Brandt", "Ilkay Gündogan", "Julian Draxler", "Leroy Sane", "Marco Reus", "Thomas Müller", "Mesut Özil"], ["---------------------", "Thomas Müller", "Mesut Özil", "Julian Draxler", "Leon Goretzka", "Leroy Sane", "Ilkay Gündogan", "Mesut Özil", "Julian Brandt"], ["---------------------", "Thomas Müller", "Mesut Özil", "Julian Draxler", "Leon Goretzka", "Leroy Sane", "Ilkay Gündogan", "Marco Reus", "Jonas Hector", "Marvin Plattenhardt", "Mesut Özil", "Julian Brandt"],
																								["---------------------", "Timo Werner", "Mario Gomez", "Thomas Müller", "Nils Petersen"]]
	},
	{"name" : "3-1-4-2",
	"position" :  																			[["---------------------", "Manuel Neuer", "Marc-Andre ter Stegen", "Bernd Leno", "Kevin Trapp"],
		["---------------------", "Joshua Kimmich", "Antonio Rüdiger", "Jerome Boateng", "Mats Hummels", "Niklas Süle", "Matthias Ginter", "Jonathan Tah"], ["---------------------", "Jerome Boateng", "Mats Hummels", "Niklas Süle", "Antonio Rüdiger", "Matthias Ginter", "Jonathan Tah"], ["---------------------", "Jonas Hector", "Marvin Plattenhardt", "Jerome Boateng", "Mats Hummels", "Niklas Süle", "Antonio Rüdiger", "Matthias Ginter", "Jonathan Tah"],
																								["---------------------", "Sami Khedira", "Toni Kroos", "Ilkay Gündogan", "Sebastian Rudy", "Mesut Özil"],
		["---------------------", "Thomas Müller", "Leon Goretzka", "Julian Brandt", "Ilkay Gündogan", "Julian Draxler", "Leroy Sane", "Marco Reus", "Mesut Özil"], ["---------------------", "Thomas Müller", "Mesut Özil", "Julian Draxler", "Leon Goretzka", "Leroy Sane", "Ilkay Gündogan", "Julian Brandt"], ["---------------------", "Thomas Müller", "Mesut Özil", "Julian Draxler", "Leon Goretzka", "Leroy Sane", "Ilkay Gündogan", "Julian Brandt"], ["---------------------", "Thomas Müller", "Mesut Özil", "Julian Draxler", "Leon Goretzka", "Leroy Sane", "Ilkay Gündogan", "Julian Brandt"],
							["---------------------", "Timo Werner", "Mario Gomez", "Thomas Müller", "Nils Petersen"], 													["---------------------", "Timo Werner", "Mario Gomez", "Thomas Müller", "Nils Petersen"]]
	}];